// import myAxios from '@config/myAxios';
import { PublicRoute } from "@config/routes/public";
import useGlobalStore from "@config/store/useGlobalStore";
import { Button, useMantineTheme } from "@mantine/core";
import Head from "next/head";

export default function HomeScreen() {
  const loading = useGlobalStore((s) => s.loading);
  const setLoading = useGlobalStore((s) => s.setLoading);
  const theme = useMantineTheme();

  // const { data, isValidating, error } = useSWR('/auth/products/all-products');	 SWR Usage
  // return isValidating ? <h1>Loading</h1> : data

  // Axios Usage
  // const api = myAxios.init();
  // const response = await api.auth.getTokens({
  //   PhoneNumber: '0000000000',
  // });

  return (
    <div className={`h-screen`}>
      <Head>
        <title>
          DMQL PROJECT
        </title>
        <meta name='description' content='Generated by itsgkram' />
        <link rel='icon' href='/src/public/favicon.ico' />
      </Head>

      <main
        className={" flex flex-col gap-3 items-center justify-center h-full"}>
        <h1 className='text-5xl'>
          DMQL PROJECT
        </h1>
        <h1 className='text-5xl'>
          Welcome to{" "}
          <a
            className='font-bold no-underline '
            style={{
              color: theme.primaryColor,
            }}
            href='https://nextjs.org'>
            Next.js!
          </a>
        </h1>

        <Button
          loading={loading}
          onClick={() => {
            setLoading(true);
            setTimeout(() => {
              setLoading(false);
            }, 2000);
          }}>
          Toogle Loading for 2 seconds
        </Button>

        <p className='text-xl '>
          Get started by editing{" "}
          <Button className='font-bold'>src/pages/index.js</Button>
        </p>

        <a
          style={{
            color: theme.primaryColor,
          }}
          className='font-bold no-underline '
          target='_blank'
          href='https://gkram.dev'>
          @gkram.dev
        </a>
      </main>
    </div>
  );
}

HomeScreen.getLayout = function getLayout(page) {
  return <PublicRoute>{page}</PublicRoute>;
};
